name: Sync Source Code to Vercel Repo

on:
  push:
    branches:
      - passkey

jobs:
  sync-to-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Push source to Vercel repo
        uses: cpina/github-action-push-to-another-repository@v1.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_TOKEN }}
        with:
          source-directory: '.'       
          destination-github-username: 'junman140'
          destination-repository-name: 'tokenization-bn'
          user-email: 'github-actions[bot]@users.noreply.github.com'
          user-name: 'GitHub Actions'
          target-branch: 'passkey'
          commit-message: 'Sync source code for Vercel build ðŸš€'
           