name: Sync to Vercel Repo

on:
  push:
    branches:
      - passkey

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git config --global --add safe.directory /github/workspace

      - name: Push to destination (Vercel) repo
        env:
          DESTINATION_REPO: "https://junman140:${{ secrets.API_TOKEN_GITHUB }}@github.com/junman140/tokenization-bn.git"
        run: |
          git clone "$DESTINATION_REPO" --branch passkey --single-branch temp_zyra_dex
          rsync -av --delete --exclude '.git' --exclude '.github/workflows' ./ temp_zyra_dex/
          cd temp_zyra_dex

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync source code for Vercel build ðŸš€ [skip ci]"
            git push origin passkey
            echo "âœ… Synced successfully!"
          else
            echo "ðŸŸ¢ No changes detected â€” skipping commit."
          fi